[discord.{{gateway_name}}]
Token="{{token}}"
Server="{{server}}" 
AutoWebhooks=true
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
# Map threads from other bridges on discord replies
PreserveThreading=true
AllowMention=["roles", "users"]